src/Entity/Books.php
<?php

namespace App\Entity;

use App\Repository\BooksRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BooksRepository::class)
 */
class Books
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titel;

    /**
     * @ORM\Column(type="integer")
     */
    private $Code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $link_pciture;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitel(): ?string
    {
        return $this->titel;
    }

    public function setTitel(string $titel): self
    {
        $this->titel = $titel;

        return $this;
    }

    public function getCode(): ?int
    {
        return $this->Code;
    }

    public function setCode(int $Code): self
    {
        $this->Code = $Code;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getLinkPciture(): ?string
    {
        return $this->link_pciture;
    }

    public function setLinkPciture(string $link_pciture): self
    {
        $this->link_pciture = $link_pciture;

        return $this;
    }
}

src/Entity/ScoreList.php
<?php

namespace App\Entity;

use App\Repository\ScoreListRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ScoreListRepository::class)
 */
class ScoreList
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Rundor;

    /**
     * @ORM\Column(type="integer")
     */
    private $vunnit;

    /**
     * @ORM\Column(type="float")
     */
    private $procent;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRundor(): ?int
    {
        return $this->Rundor;
    }

    public function setRundor(int $Rundor): self
    {
        $this->Rundor = $Rundor;

        return $this;
    }

    public function getVunnit(): ?int
    {
        return $this->vunnit;
    }

    public function setVunnit(int $vunnit): self
    {
        $this->vunnit = $vunnit;

        return $this;
    }

    public function getProcent(): ?int
    {
        return $this->procent;
    }

    public function setProcent(int $procent): self
    {
        $this->procent = $procent;

        return $this;
    }
}

templates/21_1.html.twig
{% include 'header.html.twig' %}

<form action="roll" method="post">
    <input class="button" type="submit" name="test1" id="test1" value="ROLL" /><br/>
</form>

<form action="reset" method="post">
    <input class="button" type="submit" name="reset" id="reset" value="RESET" /><br/>
</form>

<form action="stop" method="post">
    <input class="button" type="submit" name="stop" id="stop" value="STOP" /><br/>
</form>

<form action="resetscore" method="post">
    <input class="button" type="submit" name="score" id="score" value="RESET SCORE TABLE" /><br/>
</form>

<table>
<tr>
<th>Roll</th>
<th>Total</th>
</tr>
<tr>
  <th>{{ message }}</th>
  <th>{{ totale }}</th>
</tr>

</table>
<h3> {{ realmessage }} </h3>
<table>
{% for key,value in historik %}

    <tr>
    <th>Vinnare</th>
    <th>Runda</th>
    </tr>
    <tr>
      <th>{{ historik[key]['vinnare'] }} </th>
      <th>{{ historik[key]['runda'] }}</th>
    </tr>

{% endfor %}
    </table>

{% include 'footer.html.twig' %}

templates/21_2.html.twig
{% include 'header.html.twig' %}

<form action="rollTwo" method="post">
    <input class="button" type="submit" name="test1" id="test1" value="ROLL" /><br/>
</form>

<form action="resetTwo" method="post">
    <input class="button" type="submit" name="reset" id="reset" value="RESET" /><br/>
</form>

<form action="stopTwo" method="post">
    <input class="button" type="submit" name="stop" id="stop" value="STOP" /><br/>
</form>

<form action="resetscoreTwo" method="post">
    <input class="button" type="submit" name="score" id="score" value="RESET SCORE TABLE" /><br/>
</form>

<table>
<tr>
<th>Roll 1</th>
<th>Roll 2</th>
<th>Total</th>
</tr>
<tr>
  <th>{{ message }}</th>
  <th>{{ message2 }}</th>
  <th>{{ totale }}</th>
</tr>

</table>
<h3> {{ realmessage }} </h3>
<table>
{% for key,value in historik %}

    <tr>
    <th>Vinnare</th>
    <th>Runda</th>
    </tr>
    <tr>
      <th>{{ historik[key]['vinnare'] }} </th>
      <th>{{ historik[key]['runda'] }}</th>
    </tr>

{% endfor %}
    </table>
<?php

{% include 'footer.html.twig' %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/books.html.twig
{% include 'header.html.twig' %}
        <h1>Books</h1>

        <table>
        <tr>
        <th>Id</th>
        <th>Titel</th>
        <th>Code</th>
        <th>Author</th>
        <th>Picture</th>
        </tr>
        <tr>
        {% for variables in book1 %}
        <th>{{ variables.id }}</th>
        <th>{{ variables.titel }}</th>
        <th>{{ variables.code }}</th>
        <th>{{ variables.author }}</th>
        <th><img src="{{ variables.LinkPciture }}" width="200" height="300"></th>
        {% endfor %}
        </tr
        <tr>
        {% for variables in book2 %}
        <th>{{ variables.id }}</th>
        <th>{{ variables.titel }}</th>
        <th>{{ variables.code }}</th>
        <th>{{ variables.author }}</th>
        <th><img src="{{ variables.LinkPciture }}" width="200" height="300"></th>
        {% endfor %}
        </tr>
        <tr>
        {% for variables in book3 %}
        <th>{{ variables.id }}</th>
        <th>{{ variables.titel }}</th>
        <th>{{ variables.code }}</th>
        <th>{{ variables.author }}</th>
        <th><img src="{{ variables.LinkPciture }}" width="200" height="300"></th>
        {% endfor %}
        </tr>
        </table>

templates/dice.html.twig
{% include 'header.html.twig' %}
        <h3>Let's play 21</h3>
        <h4>Remember, to be qualified to get on the highscore you need to play atleast 5 turns before pressing "RESET SCORE TABLE"</h4>
        <br>
        <h4>You are only eligible to get on the highscore if you play with one die</h4>
          <form action="21_1" method="POST">
            <input class="button" type="submit" value="One die">
          </form>
          <form action="21_2" method="POST">
            <input class="button" type="submit" value="Two dice">
          </form>
{% include 'footer.html.twig' %}

templates/footer.html.twig
</main>
<footer>
    <p>This is the footer.!!</p>
</footer>
</body>
</html>

templates/header.html.twig
<html>
    <head>
      <meta charset="UTF-8">
      <title>Welcome!</title>
      <link href="{{ asset('style.css') }}" rel="stylesheet" />
    </head>
    <body>
      <header>
          <nav>
              <a href="{{ path('dice-try') }}">Test</a> |
              <a href="{{ path('dice-game') }}">21</a> |
              <a href="{{ path('books-index') }}">Books</a> |
              <a href="{{ path('highscore') }}">Highscore</a> |
          </nav>
      </header>

templates/highscore.html.twig
{% include 'header.html.twig' %}
<h3>Highscore</h3>
<table>
<tr>
<th>Plats</th>
<th>Id</th>
<th>Rundor</th>
<th>Vunnit</th>
<th>Procent</th>
</tr>
<tr>
{% for key,variables in scorelist %}
<th>{{key + 1}}</th>
<th>{{ variables.id }}</th>
<th>{{ variables.rundor }}</th>
<th>{{ variables.vunnit }}</th>
<th>{{ variables.procent }}</th>
</tr>
{% endfor %}

</table>
{% include 'footer.html.twig' %}

templates/try.html.twig
{% include 'header.html.twig' %}
        <h1>Privjet</h1>
{% include 'footer.html.twig' %}
controller: App\Controller\DefaultController::index